# Generated by Django 5.1.3 on 2024-12-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='sol',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='terrestrial_date',
            field=models.DateField(),
        ),
    ]
