version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            playwright install
            playwright install-deps
      - run:
          name: Run Django migrations
          command: |
            . venv/bin/activate
            cd mars1  # Change to the directory containing manage.py
            python manage.py migrate
      - run:
          name: Create test user
          command: |
            . venv/bin/activate
            cd mars1
            python manage.py create_test_user
      # - run:
      #     name: Create test create_test_posts
      #     command: |
      #       . venv/bin/activate
      #       cd mars1
      #       python manage.py create_test_posts
      - run:
          name: Populate Weather table
          command: |
            . venv/bin/activate
            cd mars1
            python manage.py loaddata weather/fixtures/test_weather_fixture.json
      - run:
          name: Start Django server
          command: |
            . venv/bin/activate
            cd mars1  # Change to the directory containing manage.py
            python manage.py runserver 0.0.0.0:8000
          background: true
      - run:
          name: Start xvfb
          command: |
            Xvfb :99 -screen 0 1280x1024x24 &
      - run:
          name: Wait for server to start
          command: |
            . venv/bin/activate
            until curl -s http://localhost:8000 > /dev/null; do echo "Waiting for server..."; sleep 5; done
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd mars1
            export DISPLAY=:99
            export PYTHONPATH=$PYTHONPATH:$(pwd)/tests
            pytest --junitxml=reports/test-results.xml
      - store_test_results:
          path: mars1/reports
      - store_artifacts:
          path: mars1/reports

workflows:
  version: 2
  test:
    jobs:
      - test