version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo playwright install-deps  
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest pytest-django pytest-playwright
            playwright install
      - run:
          name: Run Django migrations
          command: |
            . venv/bin/activate
            cd mars1  # Change to the directory containing manage.py
            python manage.py migrate
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd mars1  # Change to the directory containing manage.py
            pytest

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master