# Generated by Django 5.1.3 on 2024-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_id', models.IntegerField()),
                ('terrestrial_date', models.CharField(max_length=100)),
                ('sol', models.IntegerField()),
                ('ls', models.IntegerField(null=True)),
                ('season', models.CharField(max_length=20, null=True)),
                ('min_temp', models.IntegerField(null=True)),
                ('max_temp', models.IntegerField(null=True)),
                ('pressure', models.IntegerField(null=True)),
                ('pressure_string', models.CharField(max_length=100, null=True)),
                ('abs_humidity', models.CharField(max_length=100, null=True)),
                ('wind_speed', models.CharField(max_length=20, null=True)),
                ('wind_direction', models.CharField(max_length=100, null=True)),
                ('atmo_opacity', models.CharField(max_length=20, null=True)),
                ('sunrise', models.CharField(max_length=6)),
                ('sunset', models.CharField(max_length=6)),
                ('local_uv_irradiance_index', models.CharField(max_length=20, null=True)),
                ('min_gts_temp', models.IntegerField(null=True)),
                ('max_gts_temp', models.IntegerField(null=True)),
                ('source', models.CharField(default='inta-csic', max_length=100)),
            ],
            options={
                'ordering': ('-sol',),
            },
        ),
    ]
