# Generated by Django 5.1.5 on 2025-02-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
