# Generated by Django 5.1.5 on 2025-02-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
